Rails.application.routes.draw do

  post "/:id/show/answer" => "show#answer"
  get "/:id/show/top" => "show#top"
  get '/:id/show/q1' => "show#q1"
  get '/:id/show/q2' => "show#q2"
  get '/:id/show/q3' => "show#q3"
  get '/:id/show/q4' => "show#q4"
  get '/:id/show/q5' => "show#q5"
  get '/:id/show/q6' => "show#q6"
  get '/:id/show/q7' => "show#q7"
  get '/:id/show/q8' => "show#q8"
  get '/:id/show/q9' => "show#q9"
  get '/:id/show/q10' => "show#q10"
  post "show/create1" => "show#create1"
  post "show/create2" => "show#create2"
  post "show/create3" => "show#create3"
  post "show/create4" => "show#create4"
  post "show/create5" => "show#create5"
  post "show/create6" => "show#create6"
  post "show/create7" => "show#create7"
  post "show/create8" => "show#create8"
  post "show/create9" => "show#create9"
  post "show/create10" => "show#create10"
  get "/:id/show/result" => "show#result"


  get '/:id/post/new1' =>"post#new1"
  get '/:id/post/new2' =>"post#new2"
  get '/:id/post/new3' =>"post#new3"
  get '/:id/post/new4' =>"post#new4"
  get '/:id/post/new5' =>"post#new5"
  get '/:id/post/new6' =>"post#new6"
  get '/:id/post/new7' =>"post#new7"
  get '/:id/post/new8' =>"post#new8"
  get '/:id/post/new9' =>"post#new9"
  get '/:id/post/new10' =>"post#new10"

  post "post/create1" => "post#create1"
  post "post/create2" => "post#create2"
  post "post/create3" => "post#create3"
  post "post/create4" => "post#create4"
  post "post/create5" => "post#create5"
  post "post/create6" => "post#create6"
  post "post/create7" => "post#create7"
  post "post/create8" => "post#create8"
  post "post/create9" => "post#create9"
  post "post/create10" => "post#create10"


  get '/' => "home#top"

  get 'signup' => "user#new"
  post "create" => "user#create"
  post "login" => "user#login"
  get "login_form" => "user#login_form"
  get "/:id/menu" => "home#menu"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
